### ISSUE TITLE
Issue Reading Delta Tables from Spark through databricks connect

### ISSUE THREAD

**Issue by chocwaffles** [cran/SparkR#2]
Why can't I read delta files? when I run the same commands within databricks notebook, that works.
```r
> library(SparkR, lib.loc = .libPaths(c(file.path('c:/programdata/anaconda3/lib/site-packages/pyspark/jars"', 'R', 'lib'), .libPaths())))
> # Point to the Databricks Connect PySpark installation, e.g., /path/to/.../pyspark
> Sys.setenv(SPARK_HOME = "C:/Users/<username>/AppData/Local/spark/spark-3.1.1-bin-hadoop3.2")
> sparkR.session()
Java ref type org.apache.spark.sql.SparkSession id 1 
Warning message:
In sparkR.session() :
  Version mismatch between Spark JVM and SparkR package. JVM version was 3.1.1, while R package version was 3.1.2
> cust_tbl <- read.df(path = "/mnt/dataLake/prepared/<category>/<subcategory>/latest/", source = "delta")
Error: Error in load : java.lang.ClassNotFoundException: Failed to find data source: delta. Please find packages at http://spark.apache.org/third-party-projects.html
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:689)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:743)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:266)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.spark.api.r.RBackendHandler.handleMethodCall(RBackendHandler.scala:164)
	at org.apache.spark.api.r.RBackendHandler.channelRead0(RBackendHandler.scala:105)
	at org.apache.spark.api.r.RBackendHandler.channelRead0(RBac
```

Session info
```r
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] SparkR_3.1.2

loaded via a namespace (and not attached):
[1] compiler_4.0.5 tools_4.0.5    tinytex_0.31   xfun_0.22   
```

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors and possibly URLs in the `DESCRIPTION` file. Thanks!

**Comment by chocwaffles** [comment]
Just realised i got my path swapped incorrectly. the correct syntax below fixed it.
```r
library(SparkR, lib.loc = .libPaths(c(file.path('C:/Users/<user.name>/AppData/Local/spark/spark-3.1.1-bin-hadoop3.2', 'R', 'lib'), .libPaths())))

# Point to the Databricks Connect PySpark installation, e.g., /path/to/.../pyspark
Sys.setenv(SPARK_HOME = "c:/programdata/anaconda3/lib/site-packages/pyspark")
sparkR.session()
```
